### PR TITLE
Fix SLURM's publish_pending cron job to push the correct metric

### PR DESCRIPTION
**Pull request by rajachan**
Until now, we seemed to have been publishing the number of pending jobs
to CloudWatch when running with SLURM. This inadvertently caused really
slow scale up.

Signed-off-by: Raghu Raja <craghun@amazon.com>

### CODE REVIEW

**Comment by bwbarrett** [comment]
Testing? :)

**Comment by rajachan** [comment]
Manually tested the command when a 3-node job was pending:

```
[ec2-user@ip-172-31-33-114 ~]$ /opt/slurm/bin/squeue -r -h -o '%t %D' | awk '$1 == "PD" { total = total + 1} END {print total}'
1
[ec2-user@ip-172-31-33-114 ~]$ /opt/slurm/bin/squeue -r -h -o '%t %D' | awk '$1 == "PD" { total = total + $2} END {print total}'
3
```

I've kicked off a cluster with my custom cookbook. Will report back with a 👍 / 👎 .

**Comment by rajachan** [comment]
Test with custom cookbook went as expected. SLURM clusters are now pushing number of nodes required for pending jobs to the CW metric.

**Comment by sean-smith** [comment]
This isn't correct either. I ran this with a *running* job that required 2 nodes and it still returned 2.

```
[ec2-user@ip-172-31-62-167 ~]$ /opt/slurm/bin/squeue -r -h -o '%t %D'
R 2
[ec2-user@ip-172-31-62-167 ~]$ /opt/slurm/bin/squeue -r -h -o '%t %D' | awk '$1 = "PD" {total = total + $2} END {print total}'
2
[ec2-user@ip-172-31-62-167 ~]$ squeue
             JOBID PARTITION     NAME     USER ST       TIME  NODES NODELIST(REASON)
                56   compute hellowor ec2-user  R       4:25      2 ip-172-31-52-51,ip-172-31-53-10
```

**Pull request merged**
